name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy_v1:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속하기
        uses: appleboy/ssh-action@v1.2.1
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script-stop: true
          script: |
            cd /home/ubuntu/nest-cicd-ec2
            rm -rf .env
            git pull origin main
            echo "${ENV}" > .env
            npm install
            npm run build
            pm2 kill
            pm2 start dist/main.js --name "backend-server"
