name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy_v1:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속하기
      # 라이브러리 사용 https://github.com/marketplace : github actions에서 사용할 수 있는 라이브러리
      # https://github.com/marketplace/actions/ssh-remote-commands : ssh로 원격 접속을 통해 ec2에 접속
      - uses: appleboy/ssh-action@v1.2.1
      - with:
          host: ${{ secrets.EC2_HOST }} # EC2 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 사용자
          key: ${{ secrets.EC2_KEY }} # EC2 SSH-Key
          script: 'cd /home/ubuntu/nestjs && git pull origin main && npm install && npm run start:prod'
